images:
  - name: ws-server
    newName: free17/ws-server
    newTag: v2
  - name: http-hello
    newName: registry.k8s.io/e2e-test-images/agnhost
    newTag: latest
resources:
  - https://raw.githubusercontent.com/istio/istio/master/manifests/charts/istio-operator/crds/crd-operator.yaml
  - https://raw.githubusercontent.com/istio/istio/master/manifests/charts/istio-operator/files/gen-operator.yaml
  - https://github.com/cert-manager/cert-manager/releases/download/v1.13.2/cert-manager.yaml
  - cluster-issuer.yaml
  - ingress.yaml
  - deployment.yaml
  - service.yaml
  - virtual-service.yaml
  - certificate.yaml