version: '3'

services:
  master:
    build:
      context: .
    ports:
     - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H ws://host.docker.internal:9001
    
  
  worker:
    build:
      context: .
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master