images:
  - name: ws-server
    newName: free17/ws-server
    newTag: v2
resources:
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.8.2/deploy/static/provider/do/deploy.yaml
  - ingress.yaml
  - deployment.yaml
  - service.yaml