apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
spec:
  replicas: 5
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      containers:
      - name: locust
        image: locust
        imagePullPolicy: Always
        args:
          - -f
          - ./locustfile.py
          - --worker
          - --master-host
          - locust-master
        resources:
          requests:
            memory: "128Mi"
            cpu: "2"
          limits:
            {}

