apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master
spec:
  selector:
    matchLabels:
      app: locust-master
  template:
    metadata:
      labels:
        app: locust-master
    spec:
      containers:
      - name: locust
        image: locust
        command:
          - -f
          - /mnt/locust/locustfile.py
          - --worker
          - --master-host
          - locust-master
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            {}
        ports:
        - containerPort: 8089
