apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master
spec:
  selector:
    matchLabels:
      app: locust-master
  template:
    metadata:
      labels:
        app: locust-master
    spec:
      containers:
      - name: locust
        image: locust
        imagePullPolicy: Always
        args:
          - -f
          - ./locustfile.py
          - --master
          - -H
          - ws://host.docker.internal:9001
        resources:
          requests:
            memory: "512Mi"
            cpu: "2"
          limits:
            {}
        ports:
        - containerPort: 8089
          name: http
        - containerPort: 5557
          name: locust
