apiVersion: v1
kind: Service
metadata:
  name: locust-master
spec:
  type: ClusterIP
  selector:
    app: locust-master
  ports:
  - port: 80
    targetPort: 8089
    name: http
  - port: 5557
    targetPort: 5557
    name: locust