apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ws-service
spec:
  hosts:
  - ws.do.freetale.me
  gateways:
  - ws-gateway
  http:
  - name: "ws-server"
    match:
    - uri:
        exact: /
    route:
    - destination:
        host: ws-server
        port:
          number: 80