apiVersion: v1
kind: Service
metadata:
  name: ws-server
  annotations:
    metallb.universe.tf/loadBalancerIPs: 206.189.89.68
spec:
  type: LoadBalancer
  selector:
    app: ws-server
  ports:
  - port: 80
    targetPort: 9001
